src/recaptcha/src/Listener/ValidatorFactoryResolvedListener.php, src/recaptcha/src/Middleware/ReCaptchaMiddleware.php
Fix https://github.com/friendsofhyperf/recaptcha/issues/1
=> Fix Custorm Validator should return

src/macros/output/Hyperf/HttpServer/Contract/RequestInterface.php, src/macros/src/Macros/Request/Enum.php, src/macros/src/Macros/Request/Exists.php, src/macros/src/Macros/Request/FloatMacro.php, src/macros/src/Macros/Request/Integer.php, src/macros/src/Macros/Request/Str.php, src/macros/src/Macros/Request/StringMacro.php, src/macros/src/autoload.php
Co-Authored-By: Flc゛ <14297703+flc1125@users.noreply.github.com>
=> Adds new macros for Request

src/macros/output/Hyperf/Utils/Str.php, src/macros/src/StrMacros.php, src/model-uid-addon/class_map/Hyperf/Database/Model/Concerns/HasUuids.php, src/model-uid-addon/macros/str.php, src/model-uid-addon/output/Hyperf/Utils/Str.php
- Stick with orderedUuid() in `HasUuids::newUniqueId()`
- Revert changed from `v4` to `v7` in `Str::uuid()`
=> Stick with ordered uuid

src/sentry/src/Annotation/Breadcrumb.php, src/sentry/src/Aspect/BreadcrumbAspect.php, src/sentry/src/ConfigProvider.php
```php
<?php
namespace App;
use FriendsOfHyperf\Sentry\Annotation\Breadcrumb;
class Foo
{
#[Breadcrumb(category: 'foo')]
public function bar($a = 1, $b = 2)
{
return __METHOD__;
}
}
```
=> Adds annotation and aspect

src/ide-helper/src/Alias.php, src/ide-helper/src/Command/ModelCommand.php, src/ide-helper/src/Eloquent.php
Fix https://github.com/friendsofhyperf/ide-helper/issues/1
=> Fix the bug that cannot execute `ide-helper:model`

.gitignore, src/sentry/src/Aspect/GuzzleHttpClientAspect.php
- 切片时原样记录 Options 
- Method 取值错误
https://docs.guzzlephp.org/en/stable/request-options.html
Request Options 可以由用户自由设置，且类型较多
=> Optimize: sentry guzzle aspect

src/sentry/src/Aspect/GuzzleHttpClientAspect.php
- Refactor code to make it more maintainable and extensible
- Fix bugs and add new features to existing components
=> Fix the bug that cannot get contents after aop

src/ide-helper/src/Command/ModelCommand.php
支持``ide-helper`` 使用返回的类型
场景: 在``getxxxAttribute``中固定返回类型。但是在Ide-helper生成的时候却是mixed
model:
ide_helper_model.php
=> feature: Support Ide-Helper Return Type

src/ide-helper/src/Command/ModelCommand.php
=> Fixed the bug that parameter error of implode.

src/macros/output/Hyperf/HttpServer/Contract/RequestInterface.php, src/macros/src/RequestMixin.php, tests/Macros/HttpServerRequestTest.php
Add `wantsJson` method
See:
- [Code](https://github.com/laravel/framework/blob/c13e443cd0fe5c51bcc726fb2e3cffb8ada18332/src/Illuminate/Http/Concerns/InteractsWithContentTypes.php#L34)
- [Docs](https://laravel.com/docs/10.x/requests#content-negotiation)
=> Add wantsJson method to RequestMixin

src/sentry/src/Aspect/CoroutineAspect.php, src/sentry/src/Factory/ClientBuilderFactory.php, src/sentry/src/Factory/HubFactory.php
https://github.com/friendsofhyperf/sentry/issues/5
=> Optimize Sentry

src/sentry/src/Command/AboutCommand.php, src/sentry/src/ConfigProvider.php
```shell
+------------------------------------+-------------+
| Option                             | Value       |
+------------------------------------+-------------+
| Enabled                            | MISSING DSN |
| Environment                        | dev         |
| Hyperf SDK Version                 | 3.0.0       |
| PHP SDK Version                    | 3.21.0      |
| Release                            | NOT SET     |
| Sample Rate Errors                 | 100%        |
| Sample Rate Performance Monitoring | NOT SET     |
| Sample Rate Profiling              | NOT SET     |
| Send Default PII                   | DISABLED    |
+------------------------------------+-------------+
```
=> Add `sentry:about` command

src/ide-helper/src/Command/MacroCommand.php, src/ide-helper/src/Command/ModelCommand.php, src/lock/src/Listener/RegisterPropertyHandlerListener.php, src/pretty-console/src/View/Components/Component.php, src/tinker/src/TinkerCaster.php
link: https: //www.php.net/manual/zh/reflectionproperty.setaccessible.php
=> Remove `ReflectionProperty::setAccessible`, because calling this method has no effect

src/ide-helper/composer.json, src/mysql-grammar-addon/composer.json, src/pest-plugin-hyperf/composer.json
https: //php.watch/articles/composer-prompt-require-dev-dev-packages
=> Suggest dev packages to require-dev

src/telescope/src/Listener/RequestHandledListener.php, src/telescope/src/Listener/SetRequestLifecycleListener.php
Merged after hyperf v3.0.45 is released
=> Support rpc-server request lifecycle events

src/telescope/src/IncomingEntry.php
=> Removed authenticated user

src/telescope/README.md, src/telescope/src/Telescope.php
Add custom tagging and filtering method in Telescope
=> Add custom tagging and filtering method in Telescope

src/sentry/src/HttpClient/HttpClient.php
fix https://github.com/friendsofhyperf/components/issues/619
=> Fixed the error when send event

src/notification/src/Listener/RegisterChannelsListener.php
=> feat: Update RegisterChannelsListener to use ContainerInterface for dependency injection

src/sentry/composer.json, src/sentry/src/Util/SqlParser.php
Fix https://github.com/friendsofhyperf/sentry/issues/8
=> Check whether the dependency `phpmyadmin/sql-parser` is installed

src/grpc-validation/src/Annotation/ValidationAspect.php
=> chore: Update ValidationAspect.php to include previous exception in ValidationException

src/encryption/src/Encrypter.php, src/support/src/ConfigurationUrlParser.php
=> feat: Update JSON encoding to use JSON_THROW_ON_ERROR in Encrypter and ConfigurationUrlParser

src/sentry/src/Tracing/Aspect/GuzzleHttpClientAspect.php, src/sentry/src/Tracing/Aspect/RpcAspect.php
=> chore: Skip guzzle tracing in rpc

src/model-hashids/src/ConfigProvider.php
add model-hashids publish coifng setting
=> perf: add publish coifng setting

src/model-hashids/src/Concerns/HasHashid.php
- set scope method with static
=> pref: set socpe method with static

docs/en/components/telescope.md, docs/zh_CN/components/telescope.md, src/telescope/README.md, src/telescope/composer.json, src/telescope/publish/telescope.php, src/telescope/src/Avatar.php, src/telescope/src/Command/ClearCommand.php, src/telescope/src/Command/InstallCommand.php, src/telescope/src/Command/PruneCommand.php, src/telescope/src/ConfigProvider.php, src/telescope/src/Contract/ClearableRepository.php, src/telescope/src/Contract/EntriesRepository.php, src/telescope/src/Contract/PrunableRepository.php, src/telescope/src/Contract/TerminableRepository.php, src/telescope/src/Controller/EntriesController.php, src/telescope/src/Controller/EntryController.php, src/telescope/src/EntryResult.php, src/telescope/src/IncomingEntry.php, src/telescope/src/Listener/FetchRecordingOnBootListener.php, src/telescope/src/Model/EntryModel.php, src/telescope/src/Model/EntryTagModel.php, src/telescope/src/Storage/DatabaseEntriesRepository.php, src/telescope/src/Storage/EntryQueryOptions.php, src/telescope/src/Telescope.php, src/telescope/src/TelescopeConfig.php, src/telescope/src/TelescopeContext.php
- Add query scopes to EntryModel for flexible data filtering
- Inject EntriesRepository into EntryController for better dependency management
- Simplify controller methods by using injected storage
- Add property annotations for better IDE support
- Update dependency binding in ConfigProvider
=> refactor(telescope): enhance entry storage and querying

src/telescope/migrations/2020_08_03_064816_telescope_entries.php, src/telescope/publish/telescope.php, src/telescope/src/ConfigProvider.php, src/telescope/src/Model/Model.php, src/telescope/src/Storage/DatabaseEntriesRepository.php, src/telescope/src/Storage/EntriesRepositoryFactory.php, src/telescope/src/Storage/RepositoryFactory.php, src/telescope/src/Telescope.php, src/telescope/src/TelescopeConfig.php
- Add storage driver configuration support
- Replace static config access with config() helper
- Introduce RepositoryFactory for better dependency injection
- Reorganize telescope configuration structure
- Move query_slow setting to root level of config
=> [telescope] refactor: improve configuration and storage handling

src/telescope-elasticsearch/src/Storage/EntriesIndex.php
- Add EntriesIndex class for managing Telescope entries in Elasticsearch
- Define index mapping with proper field types and settings
- Implement CRUD operations for index management
- Add error handling with logging support
- Support configurable hosts and authentication
=> feat(telescope-elasticsearch): implement elasticsearch index management

docs/en/components/telescope-elasticsearch.md, docs/zh_CN/components/telescope-elasticsearch.md, src/telescope-elasticsearch/src/Storage/EntriesIndex.php, src/telescope/src/Storage/DatabaseEntriesRepository.php, src/telescope/src/Storage/EntriesRepositoryFactory.php, src/telescope/src/TelescopeConfig.php
- Add flexible storage driver configuration support
- Support multiple storage drivers via configuration
- Add compatibility layer for v3.1 configuration
- Improve driver instance validation and error handling
- Support Closure and invokable class as drivers
=> refactor(telescope): enhance storage driver configuration

src/telescope-elasticsearch/src/Storage/ElasticsearchEntriesRepository.php, src/telescope-elasticsearch/src/Storage/EntriesIndex.php, src/telescope/src/Storage/EntriesRepositoryFactory.php, src/telescope/src/Storage/NullEntriesRepository.php, src/telescope/src/TelescopeConfig.php
- Add NullEntriesRepository as default storage driver
- Rename compatibility method for legacy config
- Update storage driver configuration structure
- Fix storage options merging with default values
=> refactor(telescope): improve storage driver configuration

docs/en/components/telescope-elasticsearch.md, docs/zh_CN/components/telescope-elasticsearch.md, src/telescope-elasticsearch/README.md, src/telescope/src/Command/InstallCommand.php
- Update English and Chinese documentation for telescope-elasticsearch component
- Update component README.md
- Modify telescope install command
=> docs(telescope-elasticsearch): update component documentation

src/macros/output/Hyperf/Context/Context.php, src/macros/src/ContextMixin.php, src/macros/src/Listener/RegisterMixinListener.php, tests/Macros/ContextTest.php
=> feat(context): Added `increment` and `decrement` methods to `Hyperf\Context\Context`
